POST http://localhost:3003/api/user
Content-Type: application/json

{
    "fullName": "Jorge Tovar",
      "user": "jtovar",
      "password": "1234",
      "email": "jtovar@test.com",
      "phone": "33110000"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
      "user": "jtovar",
      "password": "1234"
}

###

GET http://localhost:3003/api/campaigns/5eaf323d7592878c80e9efb2
Authorization: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZWIyNDczYzkwNmI2NDUwZjg3NTVlNWMiLCJ1c2VyIjoiV2FwaSIsImVtYWlsIjoiZ3VzQGd1cy5jb20iLCJpYXQiOjE1ODg4MTQxODMsImV4cCI6MTU4ODkwMDU4M30.agDPtH0bhL7LPGLEBhKAxQFnS6NDiN6c6KmuloastHc"

###

GET http://localhost:3003/api/campaign/5eb38aea3a1f344c285a7511
Authorization: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZWIyNDczYzkwNmI2NDUwZjg3NTVlNWMiLCJ1c2VyIjoiV2FwaSIsImVtYWlsIjoiZ3VzQGd1cy5jb20iLCJpYXQiOjE1ODg4MTQxODMsImV4cCI6MTU4ODkwMDU4M30.agDPtH0bhL7LPGLEBhKAxQFnS6NDiN6c6KmuloastHc"

###

GET http://localhost:3003/api/campaign/5eb3655d2203bc511c4f1900?platform="netflix"
Authorization: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZWIyNDczYzkwNmI2NDUwZjg3NTVlNWMiLCJ1c2VyIjoiV2FwaSIsImVtYWlsIjoiZ3VzQGd1cy5jb20iLCJpYXQiOjE1ODg4MTQxODMsImV4cCI6MTU4ODkwMDU4M30.agDPtH0bhL7LPGLEBhKAxQFnS6NDiN6c6KmuloastHc"



###

POST http://localhost:3003/api/campaign/
Content-Type: application/json
Authorization: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZWFmMzIzZDc1OTI4NzhjODBlOWVmYjIiLCJ1c2VyIjoianRvdmFyIiwiZW1haWwiOiJqdG92YXJAdGVzdC5jb20iLCJpYXQiOjE1ODg3MjQ2MjMsImV4cCI6MTU4ODgxMTAyM30.eq-qvljnfqK5ry1-V0tdDMlvhNT4EbIMuzDtr68tPLE"

{
      "name": "Nethacked",
      "city": "Monterrey",
      "date": "2020-05-05",
      "email": "netflix@test.com",
      "platform": "netflix",
      "creatorid": "5eaf323d7592878c80e9efb2"
}

###

PATCH http://127.0.0.1:3003/api/linkcampaign/1588815197862

###

PATCH http://localhost:3003/api/linklogin/1588726899294